### PR TITLE
Add a Yarn lock file

### PR DESCRIPTION
**Pull request by vanderwees**
Let's add a Yarn (npm alternative) lock file, so we're sure to work with the same package versions.

### CODE REVIEW

**Comment by derhuerst** [comment]
Note that people who may not use Yarn for package management won't get the same package versions.

**Comment by jfilter** [comment]
I am fine with having both, npm and yarn lock file. We can also switch to Yarn all togehter.

**Comment by derhuerst** [comment]
People will need to remember to update *both* the npm and yarn lock files. That was all I wanted to say.

**Comment by jfilter** [comment]
I get your point. Ideally, we should stick to one. Let's not overengineer it for now.

**Pull request merged**
